# -- Theme Options --
# テーマの挙動・見た目を制御するオプションです。
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light" # light か dark
autoSwitchAppearance = true

defaultThemeColor = "#FFFFFF"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "basic" # basic, hamburger, hybrid, custom
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # page, profile, custom
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
